Use /usr/bin/evn to locate python
Use '/usr/bin/env python', rather than a version specific python, since it won't be provided and generate a QA error.

This commit fixes the following error without using tricks on build process:
ERROR: enigma2-plugin-systemplugins-crossepg-0.8.6+gitrAUTOINC+9cef1d90e9-r0 do_package_qa: QA Issue: /usr/crossepg/scripts/test.py
contained in package enigma2-plugin-systemplugins-crossepg requires /usr/bin/python, but no providers found in RDEPENDS_enigma2-plugin-systemplugins-crossepg? [file-rdeps]